name: golint
on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  golint:
    name: golint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go-linter
        uses: Jerome1337/golint-action@v1.0.2
